spring:
  #  数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emswaring
    username: root
    password: "030606"

  servlet:
    #    文件上传配置
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  #  Mybatis配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


server:
  port: 1234
aliyun:
#  阿里云配置信息
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tGdimuvhdnBsJuqdRPK
    accessKeySecret: zZixPbIckTMX3xlRLIGSXUzyq0YtIa
    bucketName: web-linbin

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug